# Generated by Django 4.1.2 on 2023-03-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='themeMethod',
            field=models.CharField(default='', max_length=200),
        ),
    ]
