# Generated by Django 4.1.2 on 2023-03-20 17:09

from django.db import migrations, models
import embed_video.fields
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_new_price_occassionalcakes_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('cover', pyuploadcare.dj.models.ImageField()),
                ('image', pyuploadcare.dj.models.ImageField()),
                ('image2', pyuploadcare.dj.models.ImageField(blank=True, null=True)),
                ('image3', pyuploadcare.dj.models.ImageField(blank=True, null=True)),
                ('methodologyTitle', models.CharField(max_length=200, unique=True)),
                ('methodology', models.TextField(max_length=4000)),
                ('location', models.CharField(max_length=200, unique=True)),
                ('tag', models.CharField(max_length=200, unique=True)),
                ('youtube_Video', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='occassionalcakes',
            name='category',
        ),
        migrations.DeleteModel(
            name='WeddingCakes',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='OccassionalCakes',
        ),
    ]
