# Generated by Django 4.1.2 on 2023-03-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_project_remove_occassionalcakes_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='about',
            field=models.TextField(default='', max_length=4000),
        ),
    ]
