# Generated by Django 4.1.2 on 2023-03-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_project_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='webLink',
            field=models.URLField(default=''),
        ),
    ]
